import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
        <body
        style={{
          width:'100%',
          display:'flex',
          justifyContent:'center',
          alignContent:'center',
          flexDirection:'column',
        }}
        >
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
